name: reusable/validate
on:
  workflow_call:
    inputs:
      working_directory:
        description: 'Defines working directory'
        required: true
        type: string

      var_file_name:
        description: 'File where evironment variables are stored'
        required: true
        type: string
        
jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Set environment variables from artifacts
        shell: bash
        run: |
          cat ${{ inputs.var_file_name }} | tee -a $GITHUB_ENV

      - name: Terraform-SetupWithCloud
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: ${{ env.TF_VAR_terraform_version }}

      - name: Format
        run: |
          terraform fmt -write=false -diff -check
          
      - name: Validate
        run: |
          terraform init --backend=false
          terraform validate
