name: "Set Environment Variables from config files"
description: "A reusable action to set environment variables from a JSON file and write them to a file"
inputs:
  global_config_repo:
    description: "Repo containing global config JSON file"
    required: true
    default: cloudopsaas/global-config
  global_config_version:
    description: "Version of the global config JSON file, specified as git tag"
    required: true
  github_token:
    description: "GITHUB TOKEN for checking out private repo"
    required: true
  var_file_name:
    description: "File where we write evironment variables"
    required: true
    default: env_var_file
  global_config_file_path:
    description: "Path to the global module config JSON file"
    required: true
    default: "lz/global_config.json"
  module_config_file_path:
    description: "Path to the local module config JSON file"
    required: true
    default: "config/module_config.json"
  temp_workspace:
    description: "Name of the local folder where we checkout the global config repo"
    required: true
    default: "temp_global_config"
  cloud_env_variable_name:
    description: "Name of the env variable where we store the cloud env based on the branch name"
    required: true
    default: "TF_VAR_cloud_env"
  
runs:
  using: "composite"
  steps:
    - name: create temp workspace 
      shell: bash
      run: |
        mkdir ${{ inputs.temp_workspace }}

    - name: Checkout the global config repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.global_config_repo }}
        ref: ${{ inputs.global_config_version }} 
        token: ${{ inputs.github_token }}
        path: ${{ inputs.temp_workspace }}

    - name: Read global config JSON and set environment variables
      shell: bash
      working-directory: ${{ inputs.temp_workspace }}
      run: |
        for key in $(jq -r '.env_variables | keys[]' ${{ inputs.global_config_file_path }}); do
          value=$(jq -r ".env_variables[\"$key\"]" ${{ inputs.global_config_file_path }})
          echo "$key=$value" | tee -a $GITHUB_WORKSPACE/${{ inputs.var_file_name }}
        done

    - name: Read module config JSON and set environment variables
      shell: bash
      run: |
        for key in $(jq -r '.env_variables | keys[]' ${{ inputs.module_config_file_path }}); do
          value=$(jq -r ".env_variables[\"$key\"]" ${{ inputs.module_config_file_path }})
          # echo "$key=$value" >> $GITHUB_ENV
          echo "$key=$value" | tee -a $GITHUB_ENV $GITHUB_WORKSPACE/${{ inputs.var_file_name }}
        done

    - name: Create environment variable based on branch name
      shell: bash
      run: |
        if [[ "${GITHUB_EVENT_NAME}" == "push" ]]; then
          echo "${{ inputs.cloud_env_variable_name }}=$GITHUB_REF_NAME" >> $GITHUB_ENV
        elif [[ "${GITHUB_EVENT_NAME}" == "pull_request" ]]; then
          # echo "${{ inputs.cloud_env_variable_name }}=$GITHUB_BASE_REF" >> $GITHUB_ENV
          echo "${{ inputs.cloud_env_variable_name }}=$GITHUB_BASE_REF" | tee -a $GITHUB_ENV $GITHUB_WORKSPACE/${{ inputs.var_file_name }}
        else
          echo "No push or PR."
        fi