name: 'AWS OIDC'

on:
  # Triggers the workflow on push when both conditions (branch & paths) match
  push:
    branches:
      - main
      - dev
      - uat
      - prod

jobs:
  assume_role:
    runs-on: ubuntu-latest
    name: Assume Role
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: ls 
        run: |
          ls -a
          ls ./.github/reusable/
          pwd
      # - uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #       role-to-assume: arn:aws:iam::951100737550:role/GithubOIDC
      #       role-session-name: production-session
      #       aws-region: eu-central-1

      - name: Read config and set env
        uses: ./.github/reusable/set_config_env
        with:
          global_config_repo: cloudopsaas/global-config
          global_config_version: v1.0.0

      - name: Verify environment variables
        run: |
          echo $GITHUB_ENV

  test_env:
    runs-on: ubuntu-latest
    name: Test env
    steps:
      - name: test_env
        run: |
          echo "test env job"
          echo $GITHUB_ENV