name: reusable/plan
on:
  workflow_call:
    inputs:
      working_directory:
        description: 'Defines working directory'
        required: true
        type: string

      var_file_name:
        description: 'File where evironment variables are stored'
        required: true
        type: string
        
jobs:
  validate:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Set environment variables from artifacts
        working-directory: ${{ github.workspace }}
        run: |
          cat ${{ inputs.var_file_name }} | tee -a $GITHUB_ENV

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.github_oidc_role }}
          role-session-name: github-pipeline
          aws-region: ${{ env.TF_VAR_default_region }}

      - name: Terraform-SetupWithCloud
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VAR_terraform_version }}

      - name: Plan
        run: |
          terraform init -upgrade
          terraform plan -out=${{ env.TF_VAR_tf_plan_file_name }}
          # terraform show -json ${{ env.TF_VAR_tf_plan_file_name }}

      - name: Upload Terraform plan
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TF_VAR_tf_plan_file_name }}
          path: ${{ env.TF_VAR_tf_plan_file_name }}
          if-no-files-found: error
          retention-days: 1