name: reusable/analysis
on:
  workflow_call:
    inputs:
      working_directory:
        description: 'Defines working directory'
        required: true
        type: string
      
      var_file_name:
          description: 'File where evironment variables are stored'
          required: true
          type: string

    # secrets:
    #   githubToken:
    #     description: 'GitHub Token value'
    #     required: true

jobs:
  checkov:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Set environment variables from artifacts
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
          cat ${{ inputs.var_file_name }} | tee -a $GITHUB_ENV

      - name: Scan module with checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: ${{ inputs.working_directory }}
          quiet: false
          soft_fail: ${{ env.TF_VAR_tf_analysis_soft_fail }}
          compact: true

  tfsec:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Set environment variables from artifacts
        working-directory: ${{ github.workspace }}
        shell: bash
        run: |
          cat ${{ inputs.var_file_name }} | tee -a $GITHUB_ENV

      - name: Scan module with tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          working_directory: ${{ inputs.working_directory }}
          # github_token: ${{ secrets.githubToken }}
          soft_fail: ${{ env.TF_VAR_tf_analysis_soft_fail }}