name: 'AWS OIDC'

on:
  # Triggers the workflow on push when both conditions (branch & paths) match
  push:
    branches:
      - main
      - dev
      - uat
      - prod

jobs:
  assume_role:
    runs-on: ubuntu-latest
    name: Assume Role
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read config and set env
        uses: ./.github/reusable/set_config_env
        with:
          global_config_version: v1.0.2
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Select Github OIDC role based on branch name
        shell: bash
        run: |
          if [[ "${{ env.TF_VAR_cloud_env }}" == "dev" ]]; then
            echo "github_oidc_role=${{ env.TF_VAR_dev_github_oidc_role_arn }}" >> $GITHUB_ENV
          elif [[ "${{ env.TF_VAR_cloud_env }}" == "uat" ]]; then
            echo "github_oidc_role=${{ env.TF_VAR_uat_github_oidc_role_arn }}" >> $GITHUB_ENV
          elif [[ "${{ env.TF_VAR_cloud_env }}" == "prod" ]]; then
            echo "github_oidc_role=${{ env.TF_VAR_prod_github_oidc_role_arn }}" >> $GITHUB_ENV
          else
            echo "github_oidc_role=${{ env.TF_VAR_main_github_oidc_role_arn }}" >> $GITHUB_ENV
          fi
      
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.github_oidc_role }}
          role-session-name: github-pipeline
          aws-region: ${{ env.TF_VAR_default_region }}

      - name: Environment Variable Replacer
        uses: ./.github/reusable/env_variable_replacer
        with:
          filename: ./aws_accounts/operations/tf_backend.tf

      - name: Terraform-SetupWithCloud
        uses: hashicorp/setup-terraform@v3.1.2
        with:
          terraform_version: "1.9.4"

      - name: Validate
        shell: bash
        working-directory: ./aws_accounts/operations/
        run: |
          cat tf_backend.tf
          # terraform init

  test_env:
    runs-on: ubuntu-latest
    name: Test env
    steps:
      - name: test_env
        shell: bash
        run: |
          echo "test env job"
          echo $GITHUB_ENV