name: 'Terraform Pipeline'

on:
  # Triggers the workflow on push when both conditions (branch & paths) match
  push:
    branches:
      - dev
      - uat
      - prod

permissions:
  id-token: write
  contents: read

jobs:
  env-setup:
    runs-on: ubuntu-latest
    name: Environment setup
    env:
      VAR_FILE_NAME: env_var_file
      ORG_METADATA_REPO: cloudopsaas/global-config
      GLOBAL_CONFIG_VERSION: v1.0.10
      GLOBAL_CONFIG_FILE_PATH: lz/global_config.json
      MODULE_CONFIG_FILE_PATH: config/module_config.json
      CLOUD_ENV_VARIABLE_NAME: TF_VAR_cloud_env
      TF_ROOT_DIRECTORY: ./terraform
    outputs:
      var_file_name: ${{ env.VAR_FILE_NAME }}
      org_metadata_repo: ${{ env.ORG_METADATA_REPO }}
      tf_root_directory: ${{ env.TF_ROOT_DIRECTORY }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read config and set env
        # uses: ./.github/reusable_actions/set_config_env
        uses: ${{ env.ORG_METADATA_REPO }}/.github/reusable_actions/set_config_env@main
        with:
          global_config_repo: ${{ env.ORG_METADATA_REPO }}
          global_config_version: ${{ env.GLOBAL_CONFIG_VERSION }}
          global_config_file_path: ${{ env.GLOBAL_CONFIG_FILE_PATH }}
          module_config_file_path: ${{ env.MODULE_CONFIG_FILE_PATH }}
          cloud_env_variable_name: ${{ env.CLOUD_ENV_VARIABLE_NAME }}
          var_file_name: ${{ env.VAR_FILE_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Environment Variable Replacer
        # uses: ./.github/reusable_actions/env_variable_replacer
        uses: ${{ env.ORG_METADATA_REPO }}/.github/reusable_actions/env_variable_replacer@main
        with:
          files: |
            ${{ env.TF_ROOT_DIRECTORY }}/tf_config.tf
            ${{ env.TF_ROOT_DIRECTORY }}/input.tf
            
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./
          retention-days: 1

  terraform-validate:
    needs: env-setup
    name: Terraform Validate
    # uses: ./.github/workflows/reusable_tf_validate.yaml
    uses: ${{ needs.env-setup.outputs.org_metadata_repo }}/.github/workflows/reusable_tf_validate.yaml@main
    with:
      working_directory: ${{ needs.env-setup.outputs.tf_root_directory }}
      var_file_name: ${{ needs.env-setup.outputs.var_file_name }}

  terraform-lint:
    needs: env-setup
    name: Terraform Lint
    # uses: ./.github/workflows/reusable_tf_lint.yaml
    uses: ${{ needs.env-setup.outputs.org_metadata_repo }}/.github/workflows/reusable_tf_lint.yaml@main
    with:
      working_directory: ${{ needs.env-setup.outputs.tf_root_directory }}
      var_file_name: ${{ needs.env-setup.outputs.var_file_name }}

  terraform-analysis:
    needs: env-setup
    name: Terraform Security
    # uses: ./.github/workflows/reusable_tf_analysis.yaml
    uses: ${{ needs.env-setup.outputs.org_metadata_repo }}/.github/workflows/reusable_tf_analysis.yaml@main
    with:
      working_directory: ${{ needs.env-setup.outputs.tf_root_directory }}
      var_file_name: ${{ needs.env-setup.outputs.var_file_name }}

  terraform-plan:
    needs: [env-setup, terraform-validate, terraform-lint, terraform-analysis]
    name: Terraform Plan
    # uses: ./.github/workflows/reusable_tf_plan.yaml
    uses: ${{ needs.env-setup.outputs.org_metadata_repo }}/.github/workflows/reusable_tf_plan.yaml@main
    with:
      working_directory: ${{ needs.env-setup.outputs.tf_root_directory }}
      var_file_name: ${{ needs.env-setup.outputs.var_file_name }}

  manual-approval:
    name: Manual approval
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: manual-approval
    steps:
      - name: Job awaiting approval
        run: echo "Terraform plan was approved"
 
  terraform-apply:
    needs: [env-setup, terraform-plan, manual-approval]
    name: Terraform Apply
    # uses: ./.github/workflows/reusable_tf_apply.yaml
    uses: ${{ needs.env-setup.outputs.org_metadata_repo }}/.github/workflows/reusable_tf_apply.yaml@main
    with:
      working_directory: ${{ needs.env-setup.outputs.tf_root_directory }}
      var_file_name: ${{ needs.env-setup.outputs.var_file_name }}