name: 'Terraform Pipeline'

on:
  # Triggers the workflow on push when both conditions (branch & paths) match
  push:
    branches:
      - dev
      - uat
      - prod

permissions:
  id-token: write
  contents: read

jobs:
  env-setup:
    runs-on: ubuntu-latest
    name: Environment setup
    env:
      VAR_FILE_NAME: env_var_file
      GLOBAL_CONFIG_REPO: cloudopsaas/global-config
      GLOBAL_CONFIG_VERSION: v1.0.10
    outputs:
      var_file_name: ${{ env.VAR_FILE_NAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Read config and set env
        uses: ./.github/reusable_actions/set_config_env
        with:
          global_config_repo: ${{ env.GLOBAL_CONFIG_REPO }}
          global_config_version: ${{ env.GLOBAL_CONFIG_VERSION }}
          var_file_name: ${{ env.VAR_FILE_NAME }}
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Environment Variable Replacer
        uses: ./.github/reusable_actions/env_variable_replacer
        with:
          filename: ./terraform/tf_config.tf

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./
          retention-days: 1

  terraform-validate:
    needs: env-setup
    name: Terraform Validate
    uses: ./.github/workflows/reusable_tf_validate.yaml
    with:
      working_directory: ./terraform
      var_file_name: ${{ needs.env-setup.outputs.var_file_name }}

  terraform-lint:
    needs: env-setup
    name: Terraform Lint
    uses: ./.github/workflows/reusable_tf_lint.yaml
    with:
      working_directory: ./terraform
      var_file_name: ${{ needs.env-setup.outputs.var_file_name }}

  terraform-analysis:
    needs: env-setup
    name: Terraform Security
    uses: ./.github/workflows/reusable_tf_analysis.yaml
    with:
      working_directory: ./terraform
      var_file_name: ${{ needs.env-setup.outputs.var_file_name }}

  terraform-plan:
    needs: [env-setup, terraform-validate, terraform-lint, terraform-analysis]
    name: Terraform Plan
    uses: ./.github/workflows/reusable_tf_plan.yaml
    with:
      working_directory: ./terraform
      var_file_name: ${{ needs.env-setup.outputs.var_file_name }}

  manual-approval:
    name: Manual approval
    runs-on: ubuntu-latest
    needs: terraform-plan
    environment: manual-approval
    steps:
      - name: Job awaiting approval
        run: echo "Terraform plan was approved"
 
  terraform-apply:
    needs: [env-setup, terraform-plan, manual-approval]
    name: Terraform Apply
    uses: ./.github/workflows/reusable_tf_apply.yaml
    with:
      working_directory: ./terraform
      var_file_name: ${{ needs.env-setup.outputs.var_file_name }}